# This is a basic workflow that is nighly triggered

name: nightly_tests_CPU_py3.12

# Controls when the action will run. CRON schedule runs at mm hh dd mm yy UTC TIME
on:
  schedule:
    - cron: "0 0 * * *"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  run_tests:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Make the default shell a login shell, so that conda is initialised properly
    defaults:
      run:
        shell: bash -el {0}

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - name: Setup Miniforge
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniforge-version: latest
        python-version: "3.12"
    - name: Checkout wakis
      uses: actions/checkout@v4
      with:
        path: wakis
    - name: pip install
      run:  |
        cd wakis
        pip install .
        pip install pytest pytest-cov
        pip uninstall vtk -y
        pip install --extra-index-url https://wheels.vtk.org vtk-osmesa

    - name: Print versions
      run: conda list
    - name: Run pytest
      run:  |
        cd wakis
        python -m pytest --cov=wakis --cov-config=tests/.coveragerc --cov-report=term -v tests

